Repository bioimage-io/core-bioimage-io-python, pull requests merged in 2021-09, with the labels that each got.

#111 run tests via tox before publishing to pypi
  .github/workflows/release.yml
  setup.py
  tox.ini
Labels: ci, github_actions, testing

#110 Fix release script in CI
  .github/workflows/release.yml
  setup.py
  tox.ini
Labels: bug, ci, github_actions

#112 reflect rename of repo from python-bioimage-io to core-bioimage-io-python
  README.md
  conda-recipe/meta.yaml
  setup.py
Labels: documentation

#113 Add hpa model to onnx models
  tests/conftest.py
Labels: enhancement

#115 accept URLs in test-model command
  bioimageio/core/__main__.py
  bioimageio/core/prediction.py
Labels: testing

#117 Update build_model for changed output shape spec; add test
  bioimageio/core/build_spec/build_model.py
  tests/build_spec/test_build_spec.py
Labels: enhancement, testing
