Repository bioimage-io/core-bioimage-io-python, pull requests merged in 2021-12, with the labels that each got.

#174 Update to v0.4
  bioimageio/core/build_spec/build_model.py
  bioimageio/core/prediction_pipeline/_model_adapters/_keras_model_adapter.py
  bioimageio/core/prediction_pipeline/_model_adapters/_pytorch_model_adapter.py
  bioimageio/core/resource_io/nodes.py
  bioimageio/core/weight_converter/torch/utils.py
  tests/build_spec/test_build_spec.py
  tests/test_cli.py
Labels: bug, enhancement

#176 More tf features
  .github/workflows/build.yml
  bioimageio/core/__main__.py
  bioimageio/core/build_spec/build_model.py
  bioimageio/core/prediction_pipeline/_model_adapters/_keras_model_adapter.py
  bioimageio/core/prediction_pipeline/_model_adapters/_tensorflow_model_adapter.py
  bioimageio/core/weight_converter/keras/__init__.py
  bioimageio/core/weight_converter/keras/tensorflow.py
  dev/environment-tf.yaml
  tests/build_spec/test_build_spec.py
  tests/conftest.py
  tests/test_cli.py
  tests/weight_converter/keras/test_tensorflow.py
  tests/weight_converter/torch/test_torchscript.py
Labels: ci, github_actions

#177 Rename pytorch_script to torchscript
  .github/workflows/build.yml
  bioimageio/core/__main__.py
  bioimageio/core/build_spec/build_model.py
  bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py
  bioimageio/core/prediction_pipeline/_model_adapters/_torchscript_model_adapter.py
  bioimageio/core/resource_io/nodes.py
  bioimageio/core/weight_converter/torch/__init__.py
  bioimageio/core/weight_converter/torch/torchscript.py
  tests/build_spec/test_build_spec.py
  tests/prediction_pipeline/test_device_management.py
  tests/prediction_pipeline/test_prediction_pipeline.py
  tests/weight_converter/torch/test_torchscript.py
Labels: ci, github_actions

#179 Add cover generation and default license to build_model, make input/o…
  bioimageio/core/build_spec/__init__.py
  bioimageio/core/build_spec/add_weights.py
  bioimageio/core/build_spec/build_model.py
  tests/build_spec/test_add_weights.py
  tests/build_spec/test_build_spec.py
Labels: enhancement

#180 Some more fixes for build_model, update example notebook
  bioimageio/core/__main__.py
  bioimageio/core/build_spec/build_model.py
  example/.gitignore
  example/bioimageio-core-usage.ipynb
  tests/test_cli.py
Labels: bug

#181 Small post-release clean up
  README.md
  bioimageio/core/weight_converter/keras/tensorflow.py
  tests/build_spec/test_build_spec.py
Labels: documentation

#184 Check that samples are packaged in build_spec tests
  bioimageio/core/build_spec/build_model.py
  tests/build_spec/test_build_spec.py
Labels: testing

#185 Test for issue with attachments
  bioimageio/core/build_spec/build_model.py
  tests/build_spec/test_build_spec.py
Labels: testing

#191 refactor some io functionality to spec
  bioimageio/core/build_spec/build_model.py
  bioimageio/core/resource_io/__init__.py
  bioimageio/core/resource_io/io_.py
  bioimageio/core/resource_io/nodes.py
  bioimageio/core/resource_io/utils.py
  tests/build_spec/test_build_spec.py
  tests/resource_io/test_load_rdf.py
Labels: refactoring
