Repository bioimage-io/core-bioimage-io-python, pull requests merged in 2021-11, with the labels that each got.

#138 Support more dependency managers in build_model
  bioimageio/core/build_spec/build_model.py
Labels: enhancement

#140 Add --version option
  bioimageio/core/__main__.py
  setup.py
Labels: enhancement

#141 Add debug_model function
  bioimageio/core/prediction_pipeline/_prediction_pipeline.py
  bioimageio/core/resource_tests.py
Labels: enhancement

#147 Fix specifying weight format in CLI (#144)
  bioimageio/core/__main__.py
  tests/test_cli.py
Labels: bug

#149 Add more tests for weight_format
  tests/test_cli.py
  tests/test_prediction.py
Labels: enhancement, testing

#153 Update package command and clean up root_path
  bioimageio/core/__main__.py
  bioimageio/core/commands.py
  bioimageio/core/resource_io/io_.py
  bioimageio/core/resource_io/utils.py
  tests/test_cli.py
Labels: bug

#156 Fix torchscript prediction with GPU
  bioimageio/core/prediction_pipeline/_model_adapters/_torchscript_model_adapter.py
Labels: bug

#159 Improve test-model
  bioimageio/core/resource_tests.py
  tests/conftest.py
  tests/test_resource_tests/test_test_model.py
Labels: testing

#155 add unload for PredictionPipeline and ModelAdapters
  bioimageio/core/prediction_pipeline/_model_adapters/_keras_model_adapter.py
  bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py
  bioimageio/core/prediction_pipeline/_model_adapters/_onnx_model_adapter.py
  bioimageio/core/prediction_pipeline/_model_adapters/_pytorch_model_adapter.py
  bioimageio/core/prediction_pipeline/_model_adapters/_tensorflow_model_adapter.py
  bioimageio/core/prediction_pipeline/_model_adapters/_torchscript_model_adapter.py
  bioimageio/core/prediction_pipeline/_prediction_pipeline.py
  bioimageio/core/utils.py
  tests/prediction_pipeline/test_device_management.py
Labels: enhancement

#161 Fix tiling
  bioimageio/core/prediction.py
  dev/environment-torch.yaml
  tests/conftest.py
  tests/test_prediction.py
Labels: bug

#163 Fix shape val
  bioimageio/core/__main__.py
  bioimageio/core/commands.py
  bioimageio/core/resource_tests.py
  tests/conftest.py
  tests/test_cli.py
  tests/test_prediction.py
  tests/test_resource_tests/test_test_model.py
Labels: bug

#151 Add deepimagej config generation
  bioimageio/core/build_spec/build_model.py
  bioimageio/core/resource_io/utils.py
  dev/environment-base.yaml
  dev/environment-tf.yaml
  dev/environment-torch.yaml
  tests/build_spec/test_build_spec.py
Labels: enhancement

#169 Fix issues with build_model with deepimagej config
  bioimageio/core/build_spec/build_model.py
  tests/build_spec/test_build_spec.py
Labels: bug

#172 Fix more deepimagej issues
  bioimageio/core/build_spec/build_model.py
Labels: bug
