Repository bioimage-io/core-bioimage-io-python, pull requests merged in 2022-01, with the labels that each got.

#199 Fix issues and extend tiling functionality
  bioimageio/core/build_spec/build_model.py
  bioimageio/core/prediction.py
  dev/environment-tf.yaml
  tests/conftest.py
  tests/test_prediction.py
Labels: bug

#201 Extend tests for build_spec functionality
  bioimageio/core/build_spec/add_weights.py
  tests/build_spec/test_add_weights.py
  tests/build_spec/test_build_spec.py
  tests/weight_converter/keras/test_tensorflow.py
Labels: testing

#202 Fix clean-up in build_spec.add_weights
  bioimageio/core/build_spec/add_weights.py
Labels: bug, enhancement

#206 Fix test-resource
  bioimageio/core/__main__.py
  bioimageio/core/resource_io/nodes.py
Labels: bug, testing

#216 add human readable test name to resource test summary
  bioimageio/core/resource_tests.py
Labels: enhancement, testing
