Repository bioimage-io/core-bioimage-io-python, pull requests merged in 2022-02, with the labels that each got.

#218 require current latest spec version
  setup.py
Labels: testing

#222 add keys to test summary
  bioimageio/core/resource_tests.py
Labels: enhancement, testing

#226 Fix mode fixed with axes
  bioimageio/core/prediction_pipeline/_combined_processing.py
  bioimageio/core/prediction_pipeline/_processing.py
  bioimageio/core/statistical_measures.py
  tests/prediction_pipeline/test_preprocessing.py
Labels: bug

#227 fix spec imports
  bioimageio/core/build_spec/build_model.py
  bioimageio/core/resource_io/utils.py
Labels: bug

#230 Remove enforce min shape
  bioimageio/core/prediction_pipeline/_prediction_pipeline.py
  dev/environment-torch.yaml
Labels: removal

#232 catch more errors in test_model
  bioimageio/core/resource_tests.py
Labels: testing

#233 Add training data
  bioimageio/core/build_spec/build_model.py
  example/bioimageio-core-usage.ipynb
  tests/build_spec/test_build_spec.py
Labels: enhancement
